    <?php
	class Hist_ant_per_fa_m extends CI_Controller {
    public function __construct() {
        parent::__construct();
     
    }
	
	
	
	
	
	public function updateAntPerFam() {
	
            $check_all       = $this->input->post('check_all');
            $check_all1      = (isset($check_all)) ? 1 : 0;
			
            $car_nin_check    = $this->input->post('car_nin_check');
            $car_nin_check1   = (isset($car_nin_check)) ? 1 : 0;
            $madre_check      = $this->input->post('madre_check');
            $madre_check1     = (isset($madre_check)) ? 1 : 0;
            $padre_check      = $this->input->post('padre_check');
            $padre_check1     = (isset($padre_check)) ? 1 : 0;
            $car_h_check      = $this->input->post('car_h_check');
            $car_h_check1     = (isset($car_h_check)) ? 1 : 0;
            $car_pe_check     = $this->input->post('car_pe_check');
            $car_pe_check1    = (isset($car_pe_check)) ? 1 : 0;
            $nin_check2       = $this->input->post('nin_check2');
            $nin_check22      = (isset($nin_check2)) ? 1 : 0;
            $madre_check2     = $this->input->post('madre_check2');
            $madre_check22    = (isset($madre_check2)) ? 1 : 0;
            $padre_check2     = $this->input->post('padre_check2');
            $padre_check22    = (isset($padre_check2)) ? 1 : 0;
            $h_check2         = $this->input->post('h_check2');
            $h_check22        = (isset($h_check2)) ? 1 : 0;
            $pe_check2        = $this->input->post('pe_check2');
            $pe_check22       = (isset($pe_check2)) ? 1 : 0;
            $nin_check3       = $this->input->post('nin_check3');
            $nin_check33      = (isset($nin_check3)) ? 1 : 0;
            $madre_check3     = $this->input->post('madre_check3');
            $madre_check33    = (isset($madre_check3)) ? 1 : 0;
            $padre_check3     = $this->input->post('padre_check3');
            $padre_check33    = (isset($padre_check3)) ? 1 : 0;
            $h_check3         = $this->input->post('h_check3');
            $h_check33        = (isset($h_check3)) ? 1 : 0;
            $pe_check3        = $this->input->post('pe_check3');
            $pe_check33       = (isset($pe_check3)) ? 1 : 0;
            $nin_check4       = $this->input->post('nin_check4');
            $nin_check44      = (isset($nin_check4)) ? 1 : 0;
            $madre_check4     = $this->input->post('madre_check4');
            $madre_check44    = (isset($madre_check4)) ? 1 : 0;
            $padre_check4     = $this->input->post('padre_check4');
            $padre_check44    = (isset($padre_check4)) ? 1 : 0;
            $h_check4         = $this->input->post('h_check4');
            $h_check44        = (isset($h_check4)) ? 1 : 0;
            $pe_check4        = $this->input->post('pe_check4');
            $pe_check44       = (isset($pe_check4)) ? 1 : 0;
            $nin_check5       = $this->input->post('nin_check5');
            $nin_check55      = (isset($nin_check5)) ? 1 : 0;
            $madre_check5     = $this->input->post('madre_check5');
            $madre_check55    = (isset($madre_check5)) ? 1 : 0;
            $padre_check5     = $this->input->post('padre_check5');
            $padre_check55    = (isset($padre_check5)) ? 1 : 0;
            $h_check5         = $this->input->post('h_check5');
            $h_check55        = (isset($h_check5)) ? 1 : 0;
            $pe_check5        = $this->input->post('pe_check5');
            $pe_check55       = (isset($pe_check5)) ? 1 : 0;
            $nin_check05      = $this->input->post('nin_check05');
            $nin_check055     = (isset($nin_check05)) ? 1 : 0;
            $madre_check05    = $this->input->post('madre_check05');
            $madre_check055   = (isset($madre_check05)) ? 1 : 0;
            $padre_check05    = $this->input->post('padre_check05');
            $padre_check055   = (isset($padre_check05)) ? 1 : 0;
            $h_check05        = $this->input->post('h_check05');
            $h_check055       = (isset($h_check05)) ? 1 : 0;
            $pe_check05       = $this->input->post('pe_check05');
            $pe_check055      = (isset($pe_check05)) ? 1 : 0;
            $nin_check6       = $this->input->post('nin_check6');
            $nin_check66      = (isset($nin_check6)) ? 1 : 0;
            $madre_check6     = $this->input->post('madre_check6');
            $madre_check66    = (isset($madre_check6)) ? 1 : 0;
            $padre_check6     = $this->input->post('padre_check6');
            $padre_check66    = (isset($padre_check6)) ? 1 : 0;
            $h_check6         = $this->input->post('h_check6');
            $h_check66        = (isset($h_check6)) ? 1 : 0;
            $pe_check6        = $this->input->post('pe_check6');
            $pe_check66       = (isset($pe_check6)) ? 1 : 0;
            $nin_check7       = $this->input->post('nin_check7');
            $nin_check77      = (isset($nin_check7)) ? 1 : 0;
            $madre_check7     = $this->input->post('madre_check7');
            $madre_check77    = (isset($madre_check7)) ? 1 : 0;
            $padre_check7     = $this->input->post('padre_check7');
            $padre_check77    = (isset($padre_check7)) ? 1 : 0;
            $h_check7         = $this->input->post('h_check7');
            $h_check77        = (isset($h_check7)) ? 1 : 0;
            $pe_check7        = $this->input->post('pe_check7');
            $pe_check77       = (isset($pe_check7)) ? 1 : 0;
            $nin_check8       = $this->input->post('nin_check8');
            $nin_check88      = (isset($nin_check8)) ? 1 : 0;
            $madre_check8     = $this->input->post('madre_check8');
            $madre_check88    = (isset($madre_check8)) ? 1 : 0;
            $padre_check8     = $this->input->post('padre_check8');
            $padre_check88    = (isset($padre_check8)) ? 1 : 0;
            $h_check8         = $this->input->post('h_check8');
            $h_check88        = (isset($h_check8)) ? 1 : 0;
            $pe_check8        = $this->input->post('pe_check8');
            $pe_check88       = (isset($pe_check8)) ? 1 : 0;
            $nin_check9       = $this->input->post('nin_check9');
            $nin_check99      = (isset($nin_check9)) ? 1 : 0;
            $madre_check9     = $this->input->post('madre_check9');
            $madre_check99    = (isset($madre_check9)) ? 1 : 0;
            $padre_check9     = $this->input->post('padre_check9');
            $padre_check99    = (isset($padre_check9)) ? 1 : 0;
            $h_check9         = $this->input->post('h_check9');
            $h_check99        = (isset($h_check9)) ? 1 : 0;
            $pe_check9        = $this->input->post('pe_check9');
            $pe_check99       = (isset($pe_check9)) ? 1 : 0;
            $nin_check10      = $this->input->post('nin_check10');
            $nin_check1010    = (isset($nin_check10)) ? 1 : 0;
            $madre_check10    = $this->input->post('madre_check10');
            $madre_check1010  = (isset($madre_check10)) ? 1 : 0;
            $padre_check10    = $this->input->post('padre_check10');
            $padre_check1010  = (isset($padre_check10)) ? 1 : 0;
            $h_check10        = $this->input->post('h_check10');
            $h_check1010      = (isset($h_check10)) ? 1 : 0;
            $pe_check10       = $this->input->post('pe_check10');
            $pe_check1010     = (isset($pe_check10)) ? 1 : 0;
            $nin_check11      = $this->input->post('nin_check11');
            $nin_check1111    = (isset($nin_check11)) ? 1 : 0;
            $madre_check11    = $this->input->post('madre_check11');
            $madre_check1111  = (isset($madre_check11)) ? 1 : 0;
            $padre_check11    = $this->input->post('padre_check11');
            $padre_check1111  = (isset($padre_check11)) ? 1 : 0;
            $h_check11        = $this->input->post('h_check11');
            $h_check1111      = (isset($h_check11)) ? 1 : 0;
            $pe_check11       = $this->input->post('pe_check11');
            $pe_check1111     = (isset($pe_check11)) ? 1 : 0;
            $neop_check12     = $this->input->post('neop_check12');
            $neop_check1212   = (isset($neop_check12)) ? 1 : 0;
            $madre_check12    = $this->input->post('madre_check12');
            $madre_check1212  = (isset($madre_check12)) ? 1 : 0;
            $padre_check12    = $this->input->post('padre_check12');
            $padre_check1212  = (isset($padre_check12)) ? 1 : 0;
            $h_check12        = $this->input->post('h_check12');
            $h_check1212      = (isset($h_check12)) ? 1 : 0;
            $pe_check12       = $this->input->post('pe_check12');
            $pe_check1212     = (isset($pe_check12)) ? 1 : 0;
            $psi_check13      = $this->input->post('psi_check13');
            $psi_check1313    = (isset($psi_check13)) ? 1 : 0;
            $madre_check13    = $this->input->post('madre_check13');
            $madre_check1313  = (isset($madre_check13)) ? 1 : 0;
            $padre_check13    = $this->input->post('padre_check13');
            $padre_check1313  = (isset($padre_check13)) ? 1 : 0;
            $h_check13        = $this->input->post('h_check13');
            $h_check1313      = (isset($h_check13)) ? 1 : 0;
            $pe_check13       = $this->input->post('pe_check13');
            $pe_check1313     = (isset($pe_check13)) ? 1 : 0;
            $obs_check14      = $this->input->post('obs_check14');
            $obs_check1414    = (isset($obs_check14)) ? 1 : 0;
            $madre_check14    = $this->input->post('madre_check14');
            $madre_check1414  = (isset($madre_check14)) ? 1 : 0;
            $padre_check14    = $this->input->post('padre_check14');
            $padre_check1414  = (isset($padre_check14)) ? 1 : 0;
            $h_check14        = $this->input->post('h_check14');
            $h_check1414      = (isset($h_check14)) ? 1 : 0;
            $pe_check14       = $this->input->post('pe_check14');
            $pe_check1414     = (isset($pe_check14)) ? 1 : 0;
            $ulp_check15      = $this->input->post('ulp_check15');
            $ulp_check1515    = (isset($ulp_check15)) ? 1 : 0;
            $madre_check15    = $this->input->post('madre_check15');
            $madre_check1515  = (isset($madre_check15)) ? 1 : 0;
            $padre_check15    = $this->input->post('padre_check15');
            $padre_check1515  = (isset($padre_check15)) ? 1 : 0;
            $h_check15        = $this->input->post('h_check15');
            $h_check1515      = (isset($h_check15)) ? 1 : 0;
            $pe_check15       = $this->input->post('pe_check15');
            $pe_check1515     = (isset($pe_check15)) ? 1 : 0;
            $art_check16      = $this->input->post('art_check16');
            $art_check1616    = (isset($art_check16)) ? 1 : 0;
            $madre_check16    = $this->input->post('madre_check16');
            $madre_check1616  = (isset($madre_check16)) ? 1 : 0;
            $padre_check16    = $this->input->post('padre_check16');
            $padre_check1616  = (isset($padre_check16)) ? 1 : 0;
            $h_check16        = $this->input->post('h_check16');
            $h_check1616      = (isset($h_check16)) ? 1 : 0;
            $pe_check16       = $this->input->post('pe_check16');
            $pe_check1616     = (isset($pe_check16)) ? 1 : 0;
            $art_check016     = $this->input->post('art_check016');
            $art_check01616   = (isset($art_check016)) ? 1 : 0;
            $madre_check016   = $this->input->post('madre_check016');
            $madre_check01616 = (isset($madre_check016)) ? 1 : 0;
            $padre_check016   = $this->input->post('padre_check016');
            $padre_check01616 = (isset($padre_check016)) ? 1 : 0;
            $h_check016       = $this->input->post('h_check016');
            $h_check01616     = (isset($h_check016)) ? 1 : 0;
            $pe_check016      = $this->input->post('pe_check016');
            $pe_check01616    = (isset($pe_check016)) ? 1 : 0;
            $zika_check17     = $this->input->post('zika_check17');
            $zika_check1717   = (isset($zika_check17)) ? 1 : 0;
            $madre_check17    = $this->input->post('madre_check17');
            $madre_check1717  = (isset($madre_check17)) ? 1 : 0;
            $padre_check17    = $this->input->post('padre_check17');
            $padre_check1717  = (isset($padre_check17)) ? 1 : 0;
            $h_check17        = $this->input->post('h_check17');
            $h_check1717      = (isset($h_check17)) ? 1 : 0;
            $pe_check17       = $this->input->post('pe_check17');
            $pe_check1717     = (isset($pe_check17)) ? 1 : 0;
            $save             = array(
                'todo' => $check_all1,
                'car_nin' => $car_nin_check1,
                'car_m' => $madre_check1,
                'car_p' => $padre_check1,
                'car_h' => $car_h_check1,
                'car_pe' => $car_pe_check1,
                'car_text' => $this->input->post('car_text'),
                'hip_nin' => $nin_check22,
                'hip_m' => $madre_check22,
                'hip_p' => $padre_check22,
                'hip_h' => $h_check22,
                'hip_pe' => $pe_check22,
                'hip_text' => $this->input->post('hip_text'),
                'ec_nin' => $nin_check33,
                'ec_m' => $madre_check33,
                'ec_p' => $padre_check33,
                'ec_h' => $h_check33,
                'ec_pe' => $pe_check33,
                'ec_text' => $this->input->post('ec_text'),
                'ep_nin' => $nin_check44,
                'ep_m' => $madre_check44,
                'ep_p' => $padre_check44,
                'ep_h' => $h_check44,
                'ep_pe' => $pe_check44,
                'ep_text' => $this->input->post('ep_text'),
                'as_nin' => $nin_check55,
                'as_m' => $madre_check55,
                'as_p' => $padre_check55,
                'as_h' => $h_check55,
                'as_pe' => $pe_check55,
                'as_text' => $this->input->post('as_text'),
                'enre_nin' => $nin_check055,
                'enre_m' => $madre_check055,
                'enre_p' => $padre_check055,
                'enre_h' => $h_check055,
                'enre_pe' => $pe_check055,
                'enre_text' => $this->input->post('enre_text'),
                'tub_nin' => $nin_check66,
                'tub_m' => $madre_check66,
                'tub_p' => $padre_check66,
                'tub_h' => $h_check66,
                'tub_pe' => $pe_check66,
                'tub_text' => $this->input->post('tub_text'),
                'dia_nin' => $nin_check77,
                'dia_m' => $madre_check77,
                'dia_p' => $padre_check77,
                'dia_h' => $h_check77,
                'dia_pe' => $pe_check77,
                'dia_text' => $this->input->post('dia_text'),
                'tir_nin' => $nin_check88,
                'tir_m' => $madre_check88,
                'tir_p' => $padre_check88,
                'tir_h' => $h_check88,
                'tir_pe' => $pe_check88,
                'tir_text' => $this->input->post('tir_text'),
                'hep_tipo' => $this->input->post('hep_tipo'),
                'hep_nin' => $nin_check99,
                'hep_m' => $madre_check99,
                'hep_p' => $padre_check99,
                'hep_h' => $h_check99,
                'hep_pe' => $pe_check99,
                'hep_text' => $this->input->post('hep_text'),
                'enfr_nin' => $nin_check1010,
                'enfr_m' => $madre_check1010,
                'enfr_p' => $padre_check1010,
                'enfr_h' => $h_check1010,
                'enfr_pe' => $pe_check1010,
                'enfr_text' => $this->input->post('enfr_text'),
                'falc_nin' => $nin_check1111,
                'falc_m' => $madre_check1111,
                'falc_p' => $padre_check1111,
                'falc_h' => $h_check1111,
                'falc_pe' => $pe_check1111,
                'falc_text' => $this->input->post('falc_text'),
                'neop_nin' => $neop_check1212,
                'neop_m' => $madre_check1212,
                'neop_p' => $padre_check1212,
                'neop_h' => $h_check1212,
                'neop_pe' => $pe_check1212,
                'neop_text' => $this->input->post('neop_text'),
                'psi_nin' => $psi_check1313,
                'psi_m' => $madre_check1313,
                'psi_p' => $padre_check1313,
                'psi_h' => $h_check1313,
                'psi_pe' => $pe_check1313,
                'psi_text' => $this->input->post('psi_text'),
                'obs_nin' => $obs_check1414,
                'obs_m' => $madre_check1414,
                'obs_p' => $padre_check1414,
                'obs_h' => $h_check1414,
                'obs_pe' => $pe_check1414,
                'obs_text' => $this->input->post('obs_text'),
                'ulp_nin' => $ulp_check1515,
                'ulp_m' => $madre_check1515,
                'ulp_p' => $padre_check1515,
                'ulp_h' => $h_check1515,
                'ulp_pe' => $pe_check1515,
                'ulp_text' => $this->input->post('ulp_text'),
                'art_nin' => $art_check1616,
                'art_m' => $madre_check1616,
                'art_p' => $padre_check1616,
                'art_h' => $h_check1616,
                'art_pe' => $pe_check1616,
                'art_text' => $this->input->post('art_text'),
                'hem_nin' => $art_check01616,
                'hem_m' => $madre_check01616,
                'hem_p' => $padre_check01616,
                'hem_h' => $h_check01616,
                'hem_pe' => $pe_check01616,
                'hem_text' => $this->input->post('hem_text'),
                'zika_nin' => $zika_check1717,
                'zika_m' => $madre_check1717,
                'zika_p' => $padre_check1717,
                'zika_h' => $h_check1717,
                'zika_pe' => $pe_check1717, 
                'zika_text' => $this->input->post('zika_text'),
                'otros' => $this->input->post('otros'),
                'updated_time' =>date("Y-m-d H:i:s"),
                'updated_by' => $this->input->post('id_user')
              
               );
				
				$this->db->where('id', $this->input->post('id'));
		   $this->db->update('h_c_marque_positivo',$save);
		  
		           echo '<i class="bi bi-check-lg text-success fs-4"></i>';
	}
	
	
	
	
	
	
	
	
	
	}